Chore/add project config
Viniciusgalmeida/challenge-001 pull request #5
Opened 2024-08-27 00:11 UTC by Viniciusgalmeida

## O que foi feito?

Adição de tokens de tamanhos de fontes e adição de cores no arquivo dos tokens de cor.

## Checklist

- [x] Adicionar os tokens de tamanhos de fonte no mesmo arquivo criado na issue https://github.com/Viniciusgalmeida/challenge-001/issues/3
- [x] Substituir todas as cores no [arquivo](https://github.com/code-challenges-org/FRONT-challenge-001/blob/main/src/styles/design-tokens/colors/index.scss) do tokens de cor pelas cores do style guide

[Styles] - Add design tokens #3

2024-08-27 00:53 UTC, d3vlopes commented
`chore` e `refactor` na mensagem ficou meio estranho. Uma sugestão seria invés de `refactor` colocar `change`

2024-08-27 00:54 UTC, d3vlopes requested changes

2024-08-27 00:54 UTC, d3vlopes commented on src/styles/design-tokens/fonts/index.scss
> +
Aqui você deve adicionar os valores de  `Typography Scale`.

2024-08-29 14:41 UTC, Viniciusgalmeida commented
> `chore` e `refactor` na mensagem ficou meio estranho. Uma sugestão seria invés de `refactor` colocar `change`

Tenho uma dúvida Leandro, qual seria a melhor opção a se aplicar?

1. usar um `git rebase` para reescrever o histórico do título do commit.
2. utilizar um `git revert` para criar um novo commit com a alteração do título.
3. nenhuma das anteriores 😅.

2024-08-29 15:16 UTC, d3vlopes commented
> > `chore` e `refactor` na mensagem ficou meio estranho. Uma sugestão seria invés de `refactor` colocar `change`
> 
> Tenho uma dúvida Leandro, qual seria a melhor opção a se aplicar?
> 
> 1. usar um `git rebase` para reescrever o histórico do título do commit.
> 2. utilizar um `git revert` para criar um novo commit com a alteração do título.
> 3. nenhuma das anteriores 😅.

Você pode fazer reset e depois utilizar `git commit --amend` para alterar a mensagem do commit.

2024-10-28 22:28 UTC, d3vlopes requested changes

2024-10-28 22:28 UTC, d3vlopes commented on src/styles/design-tokens/fonts/index.scss
> +  --font-size-42: 42px;
Coloca os valores em `rem`.
O projeto está configurado para um 1rem ser igual a 10px.
https://github.com/Viniciusgalmeida/challenge-001/blob/main/src/styles/global.scss#L11-L12

2024-10-31 19:51 UTC, d3vlopes approved these changes

2024-11-06 18:31 UTC, merged